# Generated by Django 5.1.4 on 2025-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('agent', 'Agent'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
