# Generated by Django 5.1.4 on 2025-08-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('agent', 'Agent'), ('owner', 'Owner'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
