# Generated by Django 5.1.4 on 2025-02-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='airlines/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('trip_from', models.CharField(choices=[('Accra', 'Accra'), ('Kumasi', 'Kumasi')], max_length=100)),
                ('trip_to', models.CharField(choices=[('Accra', 'Accra'), ('Kumasi', 'Kumasi')], max_length=100)),
                ('trip_departure', models.DateField()),
                ('trip_return', models.DateField(blank=True, null=True)),
                ('number_of_adults', models.PositiveIntegerField(default=0)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('number_of_infants', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=20)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.airline')),
            ],
        ),
    ]
