# Generated by Django 5.1.4 on 2025-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
