# Generated by Django 5.1.4 on 2025-02-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Roundtrip', 'Roundtrip')], default='One Way', max_length=100),
        ),
    ]
