# Generated by Django 5.1.4 on 2025-02-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(default='', upload_to='properties/'),
        ),
    ]
