# Generated by Django 5.1.4 on 2025-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_property_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='kitcken',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='available',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance')], default='Available', max_length=100),
        ),
    ]
