# Generated by Django 5.1.4 on 2025-02-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rename_end_date_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenity1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity10',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity8',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity9',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
