# Generated by Django 5.1.4 on 2025-02-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_property_amenity1_alter_property_amenity10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
