# Generated by Django 5.1.4 on 2025-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
