# Generated by Django 5.1.4 on 2025-02-17 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='PropertyBooking',
        ),
    ]
