# Generated by Django 5.1.4 on 2025-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
