# Generated by Django 5.1.4 on 2025-01-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rental_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='slug',
        ),
    ]
