# Generated by Django 5.1.4 on 2025-01-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_rental_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='car',
        ),
    ]
