# Generated by Django 5.0.7 on 2025-01-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_remove_appointment_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at']},
        ),
    ]
