# Generated by Django 5.1.4 on 2025-01-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_appointment_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='drop_off_location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gps_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pick_up_location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
