# Generated by Django 5.1.4 on 2025-01-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_driver_car_driver'),
        ('rental', '0008_appointment_drop_off_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='my_site.car'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='my_site.driver'),
        ),
    ]
