# Generated by Django 5.1.4 on 2025-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_alter_rental_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
