# Generated by Django 5.1.4 on 2025-01-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
