# Generated by Django 5.1.4 on 2025-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='drop_off_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pick_up_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
