# Generated by Django 5.1.4 on 2025-01-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_payment_drop_off_location_payment_pick_up_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='momo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
