# Generated by Django 5.1.4 on 2025-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_alter_payment_momo_code_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
