# Generated by Django 5.1.4 on 2025-01-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_rename_appointment_date_appointment_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
