# Generated by Django 5.1.4 on 2025-01-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_appointment_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('\u2060Greater Accra Region', ' \u2060Greater Accra Region'), ('\u2060Ashanti Region', '\u2060Ashanti Region'), ('Western Region', 'Western Region'), ('Western North Region', 'Western North Region'), ('Eastern Region', 'Eastern Region'), ('\u2060Volta Region', '\u2060Volta Region'), ('Oti Region', 'Oti Region'), ('\u2060Northern Region', '\u2060Northern Region'), ('\u2060Savannah Region', '\u2060Savannah Region'), ('North East Region', 'North East Region'), ('Upper East Region', 'Upper East Region'), ('\u2060Upper West Region', '\u2060Upper West Region'), ('Bono Region', 'Bono Region'), ('Bono East Region', 'Bono East Region'), ('Ahafo Region', 'Ahafo Region')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rental.region'),
        ),
    ]
