# Generated by Django 5.1.4 on 2025-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_rental_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='town',
            field=models.CharField(default='', max_length=250),
        ),
    ]
