# Generated by Django 5.1.4 on 2025-01-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_rental_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='location_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.region'),
        ),
        migrations.AddField(
            model_name='payment',
            name='town',
            field=models.CharField(default='', max_length=250),
        ),
    ]
