# Generated by Django 5.1.4 on 2025-01-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_payment_location_category_payment_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='customer_email',
        ),
    ]
