# Generated by Django 5.1.4 on 2025-01-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_rental_document_number_rental_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='document_type',
            field=models.CharField(choices=[('Ghana Card', 'Ghana Card'), ('Passport', 'Passport')], default='Ghana Card', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='drop_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pick_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
