# Generated by Django 5.1.4 on 2025-01-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0013_car_vat_percentage'),
        ('rental', '0031_payment_commission_rate_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='my_site.driver'),
        ),
        migrations.AddField(
            model_name='rental',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='my_site.driver'),
        ),
    ]
