# Generated by Django 5.1.4 on 2025-01-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0034_appointment_customer_payment_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
