# Generated by Django 5.1.4 on 2025-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0035_rental_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='region',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='region',
        ),
        migrations.AddField(
            model_name='payment',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
