# Generated by Django 5.1.4 on 2025-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0037_alter_rental_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
