# Generated by Django 5.1.4 on 2025-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0038_alter_payment_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rental',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=5),
        ),
    ]
