# Generated by Django 5.1.4 on 2025-02-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0039_alter_appointment_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
    ]
