# Generated by Django 5.1.4 on 2025-02-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0040_rental_base_price_rental_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='base_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vat_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
