# Generated by Django 5.1.4 on 2025-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0043_rental_emergency_name_rental_emergency_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_returned_trip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
