# Generated by Django 5.1.4 on 2025-02-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0044_rental_is_returned_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='is_returned_trip',
            field=models.BooleanField(default=False),
        ),
    ]
