# Generated by Django 5.1.4 on 2025-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0045_alter_rental_is_returned_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='is_returned_trip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
