# Generated by Django 5.1.4 on 2025-02-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0046_alter_rental_is_returned_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_returned_trip',
        ),
    ]
