# Generated by Django 5.1.4 on 2025-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0049_alter_appointment_customer_alter_payment_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
