# Generated by Django 5.1.4 on 2025-02-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0050_rental_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='number_of_days',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
