# Generated by Django 5.1.4 on 2025-02-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0025_agent'),
        ('rental', '0051_alter_rental_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='my_site.agent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='my_site.agent'),
        ),
        migrations.AddField(
            model_name='rental',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='my_site.agent'),
        ),
    ]
