# Generated by Django 5.1.4 on 2025-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0052_appointment_agent_payment_agent_rental_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='agent_commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
