# Generated by Django 5.1.4 on 2025-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0054_rentalpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_code',
            field=models.CharField(choices=[('1441002567287', '1441002567287'), ('0597406474', '0597406474')], max_length=100),
        ),
    ]
