# Generated by Django 5.1.4 on 2025-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0055_alter_rentalpayment_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('MoMo', 'MoMo'), ('Cash', 'Cash')], max_length=100),
        ),
    ]
