# Generated by Django 5.1.4 on 2025-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0056_rentalpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_code',
            field=models.CharField(choices=[('1441002567287', '1441002567287'), ('0597406474', '0597406474'), ('cash', 'cash')], max_length=100),
        ),
    ]
