# Generated by Django 5.1.4 on 2025-02-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0057_alter_rentalpayment_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpayment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_code',
            field=models.CharField(choices=[('1441002567287', '1441002567287'), ('0597406474', '0597406474'), ('cash', 'cash'), ('cash', 'cash'), ('cash', 'cash')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('MoMo', 'MoMo'), ('Cash', 'Cash'), ('Paid to Driver', 'Paid to Driver'), ('Paid to Agent', 'Paid to Agent')], max_length=100),
        ),
    ]
