# Generated by Django 5.1.4 on 2025-05-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0058_rentalpayment_name_alter_rentalpayment_payment_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='vat_percentage',
        ),
    ]
