# Generated by Django 5.1.4 on 2025-07-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0059_remove_rental_vat_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
