# Generated by Django 5.1.4 on 2025-07-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0060_rental_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='accommodation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='chop_money',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
