# Generated by Django 5.1.4 on 2025-01-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='MyCar',
        ),
    ]
