# Generated by Django 5.1.4 on 2025-01-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
