# Generated by Django 5.1.4 on 2025-01-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
