# Generated by Django 5.1.4 on 2025-01-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
