# Generated by Django 5.1.4 on 2025-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_expense_drivers_commission_alter_expense_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('Febuary', 'Febuary'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
    ]
