# Generated by Django 5.1.4 on 2025-02-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_expense_description'),
        ('my_site', '0024_driverreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('expense', models.CharField(max_length=225)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.car')),
            ],
        ),
    ]
