# Generated by Django 5.1.4 on 2025-01-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='recipients',
        ),
    ]
