# Generated by Django 5.1.4 on 2025-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_smslog_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='recipients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
