# Generated by Django 5.1.4 on 2025-01-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_smslog_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriversSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
