# Generated by Django 5.1.4 on 2025-02-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_loadcarimagesforcustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadCarImagesForCustomer',
        ),
    ]
