# Generated by Django 5.1.4 on 2025-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_expense_driver_alter_fuelrecord_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='station_name',
            field=models.CharField(blank=True, choices=[('Shell', 'Shell'), ('Goil', 'Goil'), ('Total', 'Total'), ('ZEN', 'ZEN')], max_length=100, null=True),
        ),
    ]
