# Generated by Django 5.1.4 on 2025-01-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContractForm',
        ),
    ]
