# Generated by Django 5.1.4 on 2025-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_rename_contactform_contractform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoggasForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_title', models.CharField(default='Customer Information', max_length=100)),
                ('customer_full_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('customer_whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_digital_address', models.CharField(max_length=100)),
                ('customer_ghana_card_number', models.CharField(max_length=15)),
                ('customer_passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_title', models.CharField(default='Guarantor Information (for Self-Drive)', max_length=100)),
                ('guarantor_full_name', models.CharField(max_length=100)),
                ('guarantor_phone_number', models.CharField(max_length=15)),
                ('guarantor_digital_address', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_relationship_to_customer', models.CharField(max_length=100)),
                ('guarantor_ghana_card_number', models.CharField(max_length=15)),
                ('vehicle_title', models.CharField(default='Vehicle Details', max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_registration', models.CharField(max_length=100)),
                ('rental_title', models.CharField(default='Vehicle Rental Details', max_length=100)),
                ('return_duration', models.CharField(max_length=10)),
                ('start_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('end_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('payment_title', models.CharField(default='Payment Information', max_length=100)),
                ('self_drive_daily_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money (MoMo)', 'Mobile Money (MoMo)'), ('Bank Transfer', 'Bank Transfer')], max_length=100)),
                ('staff_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ContractForm',
        ),
    ]
