# Generated by Django 5.1.4 on 2025-01-30 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_boggasform_delete_contractform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boggasform',
            name='end_date_and_time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='boggasform',
            name='start_date_and_time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
