# Generated by Django 5.1.4 on 2025-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_alter_boggasform_end_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boggasform',
            name='end_date_and_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='boggasform',
            name='start_date_and_time',
            field=models.DateField(),
        ),
    ]
