# Generated by Django 5.1.4 on 2025-01-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_make',
        ),
    ]
