# Generated by Django 5.1.4 on 2025-01-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_remove_car_car_make'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
