# Generated by Django 5.1.4 on 2025-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_driver_commission_driver_licence_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year_registered',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
