# Generated by Django 5.1.4 on 2025-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_car_year_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
