# Generated by Django 5.1.4 on 2025-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0011_alter_car_price_outside_ashanti_to_next_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_outside_ashanti_to_next_region',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_outside_ashanti_to_next_three_regions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_outside_ashanti_to_next_two_regions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_outside_kumasi_inside_ashanti',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_within_kumasi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
