# Generated by Django 5.1.4 on 2025-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_alter_car_price_outside_ashanti_to_next_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='VAT percentage (e.g., 25 for 25%)', max_digits=5),
        ),
    ]
