# Generated by Django 5.1.4 on 2025-01-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0013_car_vat_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_outside_ashanti_to_next_region',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_outside_ashanti_to_next_three_regions',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_outside_ashanti_to_next_two_regions',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_outside_kumasi_inside_ashanti',
        ),
    ]
