# Generated by Django 5.1.4 on 2025-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0015_car_ahafo_region_price_car_ashanti_region_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='bluetooth_connectivity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gps_navigation',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
