# Generated by Django 5.1.4 on 2025-01-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0018_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery-img/'),
        ),
    ]
