# Generated by Django 5.1.4 on 2025-02-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0021_car_range_price_ahafo_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
    ]
