# Generated by Django 5.1.4 on 2025-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0025_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rental_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
