# Generated by Django 5.1.4 on 2025-04-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0026_car_rental_date_car_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
