# Generated by Django 5.1.4 on 2025-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0027_car_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_oil_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='last_oil_change_mileage',
            field=models.PositiveBigIntegerField(default=0, help_text='Mileage at last oil change (km)'),
        ),
        migrations.AddField(
            model_name='car',
            name='oil_change_default',
            field=models.PositiveBigIntegerField(default=5000, help_text='Default mileage between oil changes (km)'),
        ),
    ]
