# Generated by Django 5.1.4 on 2025-06-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0029_alter_driver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unlimited', 'Unlimited'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
