# Generated by Django 5.1.4 on 2025-08-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0031_car_registration_number'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'permissions': [('view_own_car', 'Can view own cars'), ('view_own_rentals', 'Can view rentals for own cars')]},
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cars', to='owner.owner'),
        ),
    ]
